---
title: "Class Outline"
author: "Alejandro Gonzalez"
date: "8 September 2018"
output:
  html_document: default
css: css/style.css
---

# Tourism Marketing II - Class Outline
  
  

#### Week 1:
* Monday, September 10th: Subject presentation.
* Wednesday, September 12th: Introduction to Tourism Marketing and basic concepts.
	
#### Week 2:
* Monday, September 17th: Overview of marketing plans, what is marketing and new marketing philosophy.
* Wednesday, September 19th: Marketing 3.0


These first weeks will contain the following exercises:

* Design Thinking and creativity techniques.
* Definition of Marketing.
* How to properly use academic citation.
* Find a marketing plan for touristic destinations.
* Attach minimal project schema.
* Marketing 1.0 and 3.0
* Practice delivery: Kotler's video.
* Mission and Vision
* Growth strategies
* Flipped learning: the mission.
* The Ansoff matrix


#### Week 3: Product - Lab 1. Levels of Product and creation of tourism logo.
* Monday, September 24th: 
* Wednesday, September 26th: 

#### Week 4: Product - Lab 2
* Monday, October 1st:
* Wednesday, October 3rd:

#### Week 5:
* Monday, October 8th: Product
* Wednesday, October 10th: Product
	
#### Week 6: Price - Lab 1. Book practice on price management. Answer 7 questions about the platform's price.
* Monday, October 15th:
* Wednesday, October 17th:
	
#### Week 7: Price - Lab 2. Southwest Airlines Revenue Management practice.
* Monday, October 22nd:
* Wednesday, October 24th:
	
	
#### Week 8: Placement. Search of ABC franchises and franchise opportunities.
* Monday, October 29th:
* Wednesday, October 31st:
	
#### Week 9: Placement
* Monday, November 5th:
* Wednesday, November 7th: **Mid-term exam.**
	
#### Week 10: Promotion - IMC. Discussion questions on commercial communication.
* Monday, November 12th:
* Wednesday, November 14th:
	
#### Week 11: Promotion - Advertising
* Monday, November 19th:
* Wednesday, November 21st:
	
#### Week 12: Promotion - PR and sales promotion
* Monday, November 26th: **No class.**
* Wednesday, November 28th:
	
#### Week 13: Direct Marketing. Practice on aggresive direct marketing strategies in the tourism sector.
* Monday, December  3rd:
* Wednesday, December 5th:
	
#### Week 14: Online marketing and learning revision. Most interesting advertising formats in social media.
* Monday, December 10th:
* Wednesday, December 12th: **Mid-term exam.**
	
#### Week 15: Final essay presentations
* Monday, December 17th: presentations
* Wednesday, December 19th: presentations


### Final evaluation: *23/01/2019 & 08/02/2019*
### Close of calification records: *30/01/2019 & 20/02/2019*
