---
title: "TMKT II - First Midterm"
author: "Alejandro Gonzalez"
date: "11 November 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. In the ________ of the product life cycle (PLC) sales slow down and supplies start to exceed demand

  a. growth
  b. decline
  _c. maturity_
  d. introduction
  
2. Which is an example of a good quantitative objective?
  
  a. "be successful"
  b. "excellence in customer satisfaction"
  _c. "have an occupancy of 79% next year"_
  d. "be the best in town"

3. An analysis of the primary strengths and weaknesses, objectives, strategies, and other information relative to competitors called:

  a. Primary analysis
  b. Internal analysis
  c. Secondary analysis
  d. _Competitive analysis_
  
4. Staying in a RoomMate hotel and finding in the fridge a pack of cured Iberian ham from the brand managed by the famous Spanish singer Miguel Bosé, is an example of...

  a. multi-branding
  _b. co-branding_
  c. new product development
  d. upselling
  
5. Regarding the characteristics of the Strategic Business Units (SBU), which of the following statements is not true?

  _a. It always works under a different brand._
  b. It has a manager responsible for strategic planning & profit performance.
  c. It has its own set of competitors.
  d. It is a single business or a collection of related businesses that can be planned for separately from the rest of the company.
  
  
6. SSTs are a rapidly growing means for increasing customer coproduction in food-service experiences. SSTs stands for:

  a. Sure Shot Technology
  b. Sure Selling Technique
  _c. Self-Service Technology_
  d. Self-Serving Technique
  
7. A detailed version of an idea stated in meaningful consumer terms is defined as:

  a. Product image
  b. Product idea
  _c. Product concept_
  d. None of the above
  
8. According to the Ansoff product-market expansion grid, management should first consider whether:

  _a. it should gain more market share with its current products in their current market_
  b. it should find new products for a new market
  c. it should develop new markets for its current products
  d. it should find or develop new products for its current market
  
9. The most important source of new product ideas is:

  _a. Internal Sources_
  b. Customers
  c. Board members
  d. Stockholders
  
10. The heart of any marketing plan is a careful analysis of ________ and the selection of appropriate target markets.

  a. market potential
  b. competition
  _c. available market segments_
  d. current budgets
  
11. If a hotel chain buys one of its suppliers it is engaging in what type of growth?

  a. forward integration
  b. vertical integration
  c. horizontal integration
  _d. backward integration_
  
12. The dimension of atmosphere relating to volume and pitch is called:

  a. Vocal
  _b. Aural_
  c. Visual
  d. Volume
  
13. SSTs are a rapidly growing means for increasing customer coproduction in food-service experiences. SSTs stands for:

  a. Run-out
  b. Phase-out
  _c. Drop_
  d. NOne of the above
  
14. Generally, the first section of a formal, written marketing plan would be the:

  _a. Executive summary_
  b. Positioning statement
  c. Environmental analysis
  d. Segmentation and targeting process
  
15. When a hotel restaurant allowed customers to get refillable drinks by installing a drink dispensing system, the company intended...

  a. improving he interaction between customers
  b. building a low-load atmosphere
  c. facilitating the joining stage
  _d. involving the guest as an employee_
  
16. Which of the following is not something to which brand can be positioned?

  a. Product benefits
  b. Product attributes
  _c. Product pricing_
  d. Beliefs and values

17. The final stage in the new product development process is:

  _a. Commercialization_
  b. Test marketing
  c. Idea screening
  d. Concept testing

18. The ________ product level answers the question of what is really being bought.

  a. facilitating
  _b. core_
  c. augmented
  d. supportive

19. With regard to Brand Equity, which of the following statements is incorrect?

  a. Brand Equity arises from differences in consumer response, and these differences are a result of consumer's knowledge about the brand.
  _b. A brand has positive Brand Equity when consumers react less favorably to a product and the way it is marketed when the brand is identified as compared to when it's not._
  c. For the commodity or the generic version of the product, competence is based on price.
  d. Brand equity is the added value endowed on products and services

20. The differential effect that knowing the brand name has on customer response to the product and its marketing is termed:

  a. brand presence
  b. brand liability
  _c. brand equity_
  d. brand positioning
