---
title: "Tourism Marketing II - Final Project Outline"
author: "Alejandro Gonzalez"
date: "9 September 2018"
output: html_document
css: css/style.css
---

# Marketing Plan in Practice

### 1. Situation Analysis

* Internal
* External
    + Market structure analysis
    + Market nature anaysis
    + Market evolution and trends

### 2. Situation Diagnosis

* SWOT analysis
* Competitive position matrix

### 3. Marketing Objectives

* Strategic objectives
* Effect of market maturity in the definition of marketing objectives
* Marketing objectives selection criteria

### 4. Marketing Strategies

* Portfolio strategies:
    + BCG matrix
    + Growth direction matrix (Ansoff)
    + External or internal growth
 
* Segmentation, positioning, and fidelity strategies (relation marketing, perceived value management)
* Functional strategies (product, pricing, distribution and sales, communication)

### 5. Action plans

Develop an action plan for each of the core dimensions: product, pricing, distribution and sales, communication.

### 6. Action plan prioritization

### 7. Provisional trading account

### 8. Plan monitoring indicators and metrics