---
title: "Simplified Project Outline"
author: "Alejandro Gonzalez"
date: "21 October 2018"
output: html_document
css: css/style.css
---
---


## I. THE COMPANY AND THE PRODUCT

 1. Corporate connections
  
  + Brief description of the company.
  + Mission & Vision
  + Analysis of the situation (SWOT)
  + Corporate goals and strategic objectives
  + Positioning
  + Structure of the marketing & communications department
  
 2. Segmentation and Targeting
 
 3. Product / Service
 
 + Description: including competitive advantages and innovations, if relevant. You can use the Product-level and the Life-Cycle frameworks.
 + Branding
 
## II. PROMOTION MIX
 
 1. Target Audience
 2. Communication Objectives
 3. Main messages
 4. Communication channels
 5. Customer contact: internal customers
 6. How the stakeholders perceive the organization

## III. CONCLUSIONS
 
 1. Compare the M&V statements with the messages they deliver and the perception of its stakeholders.
 2. Is the company coherent in the selection of the Promotion Mix tools, according to its corporate and marketing goals, the product, the target market and the audience?
 3. Has this company adopted the IMC framework? Is the firm image unified, the messages coordinated and consistent?
 
## IV. APPENDIX
 
## V. BIBLIOGRAPHIC REFERENCES

